<a href="https://colab.research.google.com/github/azrasm/ml-hotel-booking-analysis/blob/main/%C4%8Ci%C5%A1%C4%87enje_dataseta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/MU Projekat/hotel_bookings2(zaprljan).csv')
df.head()

/tmp/ipython-input-2658431861.py:1: DtypeWarning: Columns (11,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/MU Projekat/hotel_bookings2(zaprljan).csv')


,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,NO,3četiri2,'15,July,2_7,1,nulica,0,2,...,No Deposit,NaN,NaN,0 mjeseci i 0 dana,TRanSIeNt,0+0.0,nemam auto :(,nula,0000,01/07/2015
1,Resort Hotel,0,737,'15,7,2_7,1,nulica,0,2,...,0,NaN,NaN,0 mjeseci i 0 dana,Transient,0+0.0,0,nula,0000,01/07/2015
2,Resort Hotel,NO,7,'15,July,2_7,1,nulica,2^0,samac,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,NO,13,'15,July,2_7,1,nulica,2^0,samac,...,No Deposit,304.0,NaN,0 mjeseci i 0 dana,trAnSiEnt,75+0.0,nemam auto :(,nula,0000,02/07/2015
4,Resort Hotel,0,14,'15,7,2_7,1,nulica,2^1,2,...,No Deposit,0o360,NaN,0 mjeseci i 0 dana,Transient,98.0,0,nedovoljan,0000,03/07/2015


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype 
---  ------                          --------------   ----- 
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119390 non-null  object
 3   arrival_date_year               119390 non-null  object
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  object
 6   arrival_date_day_of_month       119390 non-null  object
 7   stays_in_weekend_nights         119390 non-null  object
 8   stays_in_week_nights            119390 non-null  object
 9   adults                          119390 non-null  object
 10  children                        119386 non-null  object
 11  babies                          119390 non-null  object
 12  meal                          

In [ ]:
df.describe()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
count,119390,119390,119390,119390,119390,119390,119390,119390,119390,119390,...,119390,103050,6797,119390,119390,119390,119390,119390,119390,119390
unique,4,4,479,3,24,53,578,17,35,14,...,6,595,527,231,7475,12549,7,12,6,1804
top,City Hotel,0,0,'16,August,3_3,17,nulica,2^1,2,...,No Deposit,9.0,****,0 mjeseci i 0 dana,Transient,62.0,0,nula,0000,21/10/2015
freq,51660,36632,6345,56707,10233,3580,3647,51998,33684,89680,...,43949,19763,659,63660,59176,1966,70525,45044,39099,942


In [ ]:
df.nunique()

,0
hotel,4
is_canceled,4
lead_time,479
arrival_date_year,3
arrival_date_month,24
arrival_date_week_number,53
arrival_date_day_of_month,578
stays_in_weekend_nights,17
stays_in_week_nights,35
adults,14


**Kolona "hotel":**

In [ ]:
df["hotel"].value_counts(dropna=False)

,count
hotel,
City Hotel,51660
CH,27670
Resort Hotel,26109
RH,13951


In [ ]:
df.loc[df["hotel"] == "CH", "hotel"] = "City Hotel"

In [ ]:
df.loc[df["hotel"] == "RH", "hotel"] = "Resort Hotel"

In [ ]:
df["hotel"].value_counts(dropna=False)

,count
hotel,
City Hotel,79330
Resort Hotel,40060


**Kolona "is_canceled":**

In [ ]:
df["is_canceled"].value_counts(dropna=False)

,count
is_canceled,
0,36632
NO,34476
YES,26771
1,21511


In [ ]:
df.loc[df["is_canceled"] == "NO", "is_canceled"] = "0"

In [ ]:
df.loc[df["is_canceled"] == "YES", "is_canceled"] = "1"

In [ ]:
df["is_canceled"] = df["is_canceled"].astype("int")

In [ ]:
df["is_canceled"].value_counts(dropna=False)

,count
is_canceled,
0,71108
1,48282


**Kolona "lead_time":**

In [ ]:
df["lead_time"].value_counts(dropna=False)

,count
lead_time,
0,6345
1,3460
2,2069
3,1816
4,1715
...,...
435,1
532,1
371,1


In [ ]:
df['lead_time'].unique()

array(['3četiri2', '737', '7', '13', '14', '0', '9', '85', '75', '23',
       '35', '68', '18', '37', '12', '72', '1dva7', '78', '48', '60',
       '77', '99', '118', '95', '96', '69', '45', '40', '15', '36', '43',
       '70', '16', '1nula7', '47', '113', '90', '50', '93', '76', '3',
       '1', '10', '5', '17', '51', '71', '63', '62', '1nula1', '2', '81',
       '3šest8', '3šest4', '3dva4', '79', '21', '1nula9', '1nula2', '4',
       '98', '92', '26', '73', '115', '86', '52', '29', '30', '33', '32',
       '8', '1nula0', '44', '80', '97', '64', '39', '34', '27', '82',
       '94', '110', '111', '84', '66', '1nula4', '28', '258', '112', '65',
       '67', '55', '88', '54', '292', '83', '1nula5', '2osam0', '394',
       '24', '1nula3', '3šest6', '2četiri9', '22', '91', '11', '1nula8',
       '1nula6', '31', '87', '41', '3nula4', '117', '59', '53', '58',
       '116', '42', '3dva1', '38', '56', '49', '317', '6', '57', '19',
       '25', '315', '1dva3', '46', '89', '61', '312', '299', '1

In [ ]:
word_to_digit = {
    "nula": "0",
    "dva": "2",
    "tri": "3",
    "četiri": "4",
    "osam": "8",
    "šest": "6"
}

import re

def decode_mixed_number(x):
    parts = re.findall(r'[0-9]+|[A-Za-zšđč枊ĐČĆŽ]+', str(x))
    result = ""
    for p in parts:
        if p.isdigit():
            result += p
        else:
            p_lower = p.lower()
            if p_lower in word_to_digit:
                result += word_to_digit[p_lower]
            else:
                result += p
    return result


df["lead_time"] = df["lead_time"].apply(decode_mixed_number)

In [ ]:
df['lead_time'].unique()

array(['342', '737', '7', '13', '14', '0', '9', '85', '75', '23', '35',
       '68', '18', '37', '12', '72', '127', '78', '48', '60', '77', '99',
       '118', '95', '96', '69', '45', '40', '15', '36', '43', '70', '16',
       '107', '47', '113', '90', '50', '93', '76', '3', '1', '10', '5',
       '17', '51', '71', '63', '62', '101', '2', '81', '368', '364',
       '324', '79', '21', '109', '102', '4', '98', '92', '26', '73',
       '115', '86', '52', '29', '30', '33', '32', '8', '100', '44', '80',
       '97', '64', '39', '34', '27', '82', '94', '110', '111', '84', '66',
       '104', '28', '258', '112', '65', '67', '55', '88', '54', '292',
       '83', '105', '280', '394', '24', '103', '366', '249', '22', '91',
       '11', '108', '106', '31', '87', '41', '304', '117', '59', '53',
       '58', '116', '42', '321', '38', '56', '49', '317', '6', '57', '19',
       '25', '315', '123', '46', '89', '61', '312', '299', '130', '74',
       '298', '119', '20', '286', '136', '129', '124', '327

In [ ]:
df["lead_time"] = df["lead_time"].astype("int")

In [ ]:
df["lead_time"].value_counts(dropna=False)

,count
lead_time,
0,6345
1,3460
2,2069
3,1816
4,1715
...,...
435,1
532,1
371,1


**Kolona "arrival_date_year":**

In [ ]:
df["arrival_date_year"].value_counts(dropna=False)

,count
arrival_date_year,
'16,56707
'17,40687
'15,21996


In [ ]:
df['arrival_date_year'].unique()

array(["'15", "'16", "'17"], dtype=object)

In [ ]:
df.loc[df["arrival_date_year"] == "'15", "arrival_date_year"] = "2015"
df.loc[df["arrival_date_year"] == "'16", "arrival_date_year"] = "2016"
df.loc[df["arrival_date_year"] == "'17", "arrival_date_year"] = "2017"

In [ ]:
df["arrival_date_year"] = df["arrival_date_year"].astype("int")

In [ ]:
df["arrival_date_year"].value_counts(dropna=False)

,count
arrival_date_year,
2016,56707
2017,40687
2015,21996


**Kolona "arrival_date_month":**

In [ ]:
df["arrival_date_month"].value_counts(dropna=False)

,count
arrival_date_month,
August,10233
July,9233
May,8690
October,8201
April,8158
June,8074
September,7739
March,7281
February,5907


In [ ]:
month_map = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

def convert_month(x):
    if isinstance(x, str) and x.capitalize() in month_map.values():
        return x.capitalize()

    try:
        num = int(str(x).strip())
        return month_map.get(num, x)
    except:
        return x

df["arrival_date_month"] = df["arrival_date_month"].apply(convert_month)

In [ ]:
df['arrival_date_month'].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [ ]:
df["arrival_date_month"] = df["arrival_date_month"].astype("string")

In [ ]:
df["arrival_date_month"].value_counts(dropna=False)

,count
arrival_date_month,
August,13877
July,12661
May,11791
October,11160
April,11089
June,10939
September,10508
March,9794
February,8068


**Kolona "arrival_date_week_number":**

In [ ]:
df["arrival_date_week_number"].value_counts(dropna=False)

,count
arrival_date_week_number,
3_3,3580
30,3087
32,3045
34,3040
18,2926
2_1,2854
28,2853
1_7,2805
20,2785


In [ ]:
df["arrival_date_week_number"] = df["arrival_date_week_number"].astype(str).str.replace("_", "")
df["arrival_date_week_number"] = df["arrival_date_week_number"].astype(int)

In [ ]:
df["arrival_date_week_number"].value_counts(dropna=False)

,count
arrival_date_week_number,
33,3580
30,3087
32,3045
34,3040
18,2926
21,2854
28,2853
17,2805
20,2785


**Kolona "arrival_date_day_of_month":**

In [ ]:
df["arrival_date_day_of_month"].value_counts(dropna=False)

,count
arrival_date_day_of_month,
17,3647
1,3626
5,3600
19,3419
2,3350
...,...
20+11,4
8+23,3
29+2,3


In [ ]:
df['arrival_date_day_of_month'].unique()

array(['1', '2', '4/2', '1+1', '6/2', '3', '1+2', '2*2', '4', '8/2',
       '1+3', '5', '10/2', '6', '5+1', '12/2', '2*3', '4+2', '3*2', '1+5',
       '7', '4+3', '14/2', '8', '2*4', '16/2', '7+1', '2+6', '6+2', '9',
       '18/2', '6+3', '8+1', '5*2', '20/2', '10', '8+2', '1+9', '2*5',
       '11', '22/2', '4*3', '2*6', '12', '24/2', '6*2', '10+2', '26/2',
       '9+4', '13', '3+10', '12+1', '5+8', '14', '2*7', '10+4', '28/2',
       '30/2', '5*3', '15', '10+5', '4+11', '3*5', '14+2', '16', '8*2',
       '32/2', '4*4', '2*8', '17', '34/2', '4+13', '18', '36/2', '3*6',
       '2+16', '2*9', '19', '6+13', '7+12', '14+5', '40/2', '20', '5*4',
       '15+5', '4*5', '21', '42/2', '11+10', '6+15', '22', '11*2',
       '11+11', '44/2', '6+17', '23', '46/2', '12+11', '24', '48/2',
       '4*6', '6+18', '12*2', '25', '22+3', '6+19', '50/2', '5*5', '21+4',
       '17+8', '4+21', '15+11', '26', '52/2', '2*13', '13*2', '3+24',
       '27', '54/2', '8+19', '10+17', '3*9', '13+14', '9*3', '7*4', '2

In [ ]:
import re
import operator

ops = {
    "+": operator.add,
    "-": operator.sub,
    "*": operator.mul,
    "/": operator.floordiv
}

def safe_eval(expr):
    expr = str(expr).strip()

    if expr.isdigit():
        return int(expr)

    match = re.fullmatch(r"(\d+)\s*([+\-*/])\s*(\d+)", expr)
    if not match:
        return None

    a, op, b = match.groups()
    a, b = int(a), int(b)

    return ops[op](a, b)

df["arrival_date_day_of_month"] = df["arrival_date_day_of_month"].apply(safe_eval)

df["arrival_date_day_of_month"] = df["arrival_date_day_of_month"].astype(int)

In [ ]:
df['arrival_date_day_of_month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
df["arrival_date_day_of_month"].value_counts(dropna=False)

,count
arrival_date_day_of_month,
17,4406
5,4317
15,4196
25,4160
26,4147
9,4096
12,4087
16,4078
2,4055


**Kolona "stays_in_weekend_nights":**

In [ ]:
df["stays_in_weekend_nights"].value_counts(dropna=False)

,count
stays_in_weekend_nights,
nulica,51998
2,33308
1,30626
4,1855
3,1259
6,153
5,79
8,60
7,19


In [ ]:
df.loc[df["stays_in_weekend_nights"] == "nulica", "stays_in_weekend_nights"] = "0"

In [ ]:
df['stays_in_weekend_nights'].unique()

array(['0', '1', '2', '4', '3', '6', '13', '8', '5', '7', '12', '9', '16',
       '18', '19', '10', '14'], dtype=object)

In [ ]:
df["stays_in_weekend_nights"] = df["stays_in_weekend_nights"].astype("int")

In [ ]:
df["stays_in_weekend_nights"].value_counts(dropna=False)

,count
stays_in_weekend_nights,
0,51998
2,33308
1,30626
4,1855
3,1259
6,153
5,79
8,60
7,19


**Kolona "stays_in_week_nights":**

In [ ]:
df["stays_in_week_nights"].value_counts(dropna=False)

,count
stays_in_week_nights,
2^1,33684
2^0,30310
3,22258
5,11077
2^2,9563
0,7645
6,1499
10,1036
7,1029


In [ ]:
import re

def decode_power_of_two(x):
    x = str(x).strip()

    if x.isdigit():
        return int(x)

    match = re.fullmatch(r"2\s*\^\s*(\d+)", x)
    if match:
        exp = int(match.group(1))
        return 2 ** exp

    return None

df["stays_in_week_nights"] = df["stays_in_week_nights"].apply(decode_power_of_two)
df["stays_in_week_nights"] = df["stays_in_week_nights"].astype(int)

In [ ]:
df['stays_in_week_nights'].unique()

array([ 0,  1,  2,  3,  4,  5, 10, 11,  8,  6,  7, 15,  9, 12, 33, 20, 14,
       16, 21, 13, 30, 19, 24, 40, 22, 42, 50, 25, 17, 32, 26, 18, 34, 35,
       41])

In [ ]:
df["stays_in_week_nights"].value_counts(dropna=False)

,count
stays_in_week_nights,
2,33684
1,30310
3,22258
5,11077
4,9563
0,7645
6,1499
10,1036
7,1029


**Kolona "adults":**

In [ ]:
df["adults"].value_counts(dropna=False)

,count
adults,
2,89680
samac,23027
3,6202
0,403
4,62
26,5
5,2
27,2
20,2


In [ ]:
df.loc[df["adults"] == "samac", "adults"] = "1"

In [ ]:
df["adults"] = df["adults"].astype("int")

In [ ]:
df['adults'].unique()

array([ 2,  1,  3,  4, 40, 26, 50, 27, 55,  0, 20,  6,  5, 10])

In [ ]:
df["adults"].value_counts(dropna=False)

,count
adults,
2,89680
1,23027
3,6202
0,403
4,62
26,5
5,2
27,2
20,2


**Kolona "children":**

In [ ]:
df["children"].value_counts(dropna=False)

,count
children,
childless,110796
1.0,4861
2.0,3652
3.0,76
NaN,4
10.0,1


In [ ]:
df['children'].unique()

array(['childless', '1.0', '2.0', '10.0', '3.0', nan], dtype=object)

In [ ]:
df.loc[df["children"] == "childless", "children"] = "0"

In [ ]:
df["children"] = (df["children"].astype("float").fillna(0).astype(int))

In [ ]:
df['children'].unique()

array([ 0,  1,  2, 10,  3])

In [ ]:
df["children"].value_counts(dropna=False)

,count
children,
0,110800
1,4861
2,3652
3,76
10,1


**Kolona "babies":**

In [ ]:
df["babies"].value_counts(dropna=False)

,count
babies,
0,85915
0,32558
1,695
1,205
2,12
2,3
10 (natalitet++),1
9 (natalitet++),1


In [ ]:
df['babies'].unique()

array([0, 1, 2, '0', '1', '2', '10 (natalitet++)', '9 (natalitet++)'],
      dtype=object)

In [ ]:
import re

def clean_babies(x):
    x = str(x).strip()

    match = re.search(r"\d+", x)
    if match:
        return int(match.group())

    return 0

df["babies"] = df["babies"].apply(clean_babies).astype(int)

In [ ]:
df['babies'].unique()

array([ 0,  1,  2, 10,  9])

In [ ]:
df["babies"].value_counts(dropna=False)

,count
babies,
0,118473
1,900
2,15
10,1
9,1


**Kolona "meal":**

In [ ]:
df["meal"].value_counts(dropna=False)

,count
meal,
BB,78015
bed and breakfast,14295
HB,12324
SC,10650
half board,2139
Undefined,1169
FB,682
full board,116


In [ ]:
df['meal'].unique()

array(['BB', 'full board', 'bed and breakfast', 'HB', 'half board', 'FB',
       'SC', 'Undefined'], dtype=object)

In [ ]:
df.loc[df["meal"] == "bed and breakfast", "meal"] = "BB"
df.loc[df["meal"] == "half board", "meal"] = "HB"
df.loc[df["meal"] == "full board", "meal"] = "FB"

In [ ]:
df["meal"].value_counts(dropna=False)

,count
meal,
BB,92310
HB,14463
SC,10650
Undefined,1169
FB,798


**Kolona "country":**

In [ ]:
df["country"].value_counts(dropna=False)

,count
country,
PRT,31902
+351,16688
GBR,7921
FRA,6987
ESP,5688
...,...
MRT,1
KIR,1
SDN,1


In [ ]:
df['country'].unique()

array(['+351', 'PRT', '+44', 'GBR', 'USA', '+34', 'IRL', 'FRA', '+353',
       nan, 'ESP', '+40', 'NOR', 'OMN', 'ARG', 'POL', '+49', '+33', '+1',
       '+32', '+41', 'DEU', 'CN', 'CHE', '+30', 'ITA', '+31', 'DNK',
       '+45', '+7', '+46', '+61', 'EST', 'RUS', 'CZE', '+55', 'BEL',
       'FIN', 'AUS', 'ROU', 'SWE', '+48', 'MOZ', 'BWA', 'LUX', '+86',
       'NLD', '+47', 'BRA', 'SVN', 'ALB', '+91', 'CHN', 'MEX', 'MAR',
       'UKR', 'SMR', 'LVA', 'PRI', 'SRB', 'IND', 'CHL', '+39', 'AUT',
       'BLR', 'LTU', '+968', 'TUR', 'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB',
       'CPV', 'ZWE', 'DZA', 'KOR', 'CRI', '+54', 'HUN', 'ARE', 'TUN',
       'JAM', 'HRV', 'HKG', 'IRN', 'GEO', 'AND', 'GIB', 'URY', 'JEY',
       'CAF', 'CYP', 'GRC', 'COL', 'GGY', 'KWT', 'NGA', '+82', 'MDV',
       'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN', 'PHL', 'SEN',
       'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD', 'MYS', '+52',
       'ARM', 'JPN', '+81', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', '

In [ ]:
import re

calling_code_map = {
    "+1": "USA",
    "+7": "RUS",
    "+44": "GBR",
    "+31": "NLD",
    "+30": "GRC",
    "+33": "FRA",
    "+34": "ESP",
    "+39": "ITA",
    "+40": "ROU",
    "+43": "AUT",
    "+45": "DNK",
    "+46": "SWE",
    "+61": "AUS",
    "+55": "BRA",
    "+47": "NOR",
    "+54": "ARG",
    "+48": "POL",
    "+81": "JPN",
    "+82": "KOR",
    "+52": "MEX",
    "+86": "CHN",
    "+91": "IND",
    "+41": "CHE",
    "+49": "DEU",
    "+32": "BEL",
    "+351": "PRT",
    "+353": "IRL",
    "+968": "OMN"
}

def clean_country(val):
    val = str(val).strip()

    if re.fullmatch(r"\+\d+", val):
        return calling_code_map.get(val, None)

    return val

df["country"] = df["country"].apply(clean_country)

In [ ]:
df["country"] = df["country"].replace(["nan", "", "NA", "N/A"], np.nan)

In [ ]:
most_common_country = df["country"].mode(dropna=True)[0]

df["country"] = df["country"].fillna(most_common_country)

In [ ]:
df['country'].unique()

array(['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', 'ROU', 'NOR', 'OMN',
       'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
       'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
       'BWA', 'LUX', 'CHN', 'SVN', 'ALB', 'IND', 'MEX', 'MAR', 'UKR',
       'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
       'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
       'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
       'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
       'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
       'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
       'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'ETH', 

In [ ]:
df["country"] = df["country"].astype("string")

In [ ]:
df["country"].value_counts(dropna=False)

,count
country,
PRT,49078
GBR,12129
FRA,10415
ESP,8568
DEU,7287
...,...
MRT,1
KIR,1
SDN,1


**Kolona "market_segment":**

In [ ]:
df["market_segment"].value_counts(dropna=False)

,count
market_segment,
0n1ine T@,56477
0ff1ine T@/T0,24219
6r0ups,19811
Direct,12606
C0rp0r@te,5295
C0mp1ement@ry,743
@vi@ti0n,237
Undefined,2


In [ ]:
def clean_market_segment(text):
    if pd.isna(text):
        return text

    mapping = {
        "@": "a",
        "6": "g",
        "0": "o",
        "1": "l"
    }

    cleaned = "".join([mapping.get(c, c) for c in text])

    return cleaned.title()

df["market_segment"] = df["market_segment"].apply(clean_market_segment)

In [ ]:
df['market_segment'].unique()

array(['Direct', 'Corporate', 'Online Ta', 'Offline Ta/To',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [ ]:
df.loc[df["market_segment"] == "Online Ta", "market_segment"] = "Online TA"
df.loc[df["market_segment"] == "Offline Ta/To", "market_segment"] = "Offline TA/TO"

In [ ]:
df["market_segment"].value_counts(dropna=False)

,count
market_segment,
Online TA,56477
Offline TA/TO,24219
Groups,19811
Direct,12606
Corporate,5295
Complementary,743
Aviation,237
Undefined,2


**Kolona "distribution_channel":**

In [ ]:
df["distribution_channel"].value_counts(dropna=False)

,count
distribution_channel,
tA/TO,6261
tA/tO,6229
Ta/to,6168
ta/to,6165
tA/to,6149
...,...
undEFined,1
undeFINed,1
undefiNeD,1


In [ ]:
df['distribution_channel'].unique()

array(['diREcT', 'dIReCt', 'DiRecT', 'corporatE', 'tA/TO', 'TA/to',
       'DiREcT', 'dIreCt', 'ta/tO', 'tA/To', 'Ta/tO', 'Ta/To', 'TA/tO',
       'Ta/TO', 'CoRpOratE', 'DIREcT', 'Ta/to', 'diRect', 'DirEcT',
       'dirECt', 'ta/to', 'TA/TO', 'dIRect', 'tA/tO', 'diREct', 'DirEct',
       'DIRECt', 'tA/to', 'ta/To', 'dIrECt', 'dirEct', 'ta/TO', 'TA/To',
       'DIReCT', 'DIREct', 'DiRECT', 'DireCt', 'DiRECt', 'DIReCt',
       'dIREcT', 'dIrEcT', 'direct', 'DIrecT', 'DireCT', 'diRecT',
       'DirECT', 'diRECT', 'cORPoRATe', 'cORPOrAte', 'CoRPoRatE',
       'dirEcT', 'direcT', 'DIreCt', 'dIreCT', 'dIrecT', 'DiReCt',
       'diReCt', 'dIrect', 'DIrEcT', 'COrPOraTe', 'dIrEct', 'DIRect',
       'dirECT', 'cOrpOrATE', 'DiReCT', 'CORPoRaTe', 'DIrECt', 'DIreCT',
       'cOrporatE', 'DirecT', 'Direct', 'dIrECT', 'DIRecT', 'diReCT',
       'DirECt', 'DIrEct', 'dIRECT', 'diRECt', 'coRpoRaTE', 'DiREct',
       'dIREct', 'DIrECT', 'CorpOraTe', 'direCT', 'DIrect', 'dIRecT',
       'CoRporate', 'DIRE

In [ ]:
channel_map = {
    "direct": "Direct",
    "corporate": "Corporate",
    "ta/to": "TA/TO",
    "gds": "GDS",
    "undefined": "Undefined"
}

df["distribution_channel"] = df["distribution_channel"].str.lower()

df["distribution_channel"] = df["distribution_channel"].map(channel_map)

In [ ]:
df['distribution_channel'].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [ ]:
df["distribution_channel"].value_counts(dropna=False)

,count
distribution_channel,
TA/TO,97870
Direct,14645
Corporate,6677
GDS,193
Undefined,5


**Kolona "is_repeated_guest":**

In [ ]:
df["is_repeated_guest"].value_counts(dropna=False)

,count
is_repeated_guest,
0,104489
novi kolačić,11091
1,3465
ponovac,345


In [ ]:
df.loc[df["is_repeated_guest"] == "novi kolačić", "is_repeated_guest"] = "0"
df.loc[df["is_repeated_guest"] == "ponovac", "is_repeated_guest"] = "1"

In [ ]:
df["is_repeated_guest"] = df["is_repeated_guest"].astype("int")

In [ ]:
df["is_repeated_guest"].value_counts(dropna=False)

,count
is_repeated_guest,
0,115580
1,3810


**Kolona "previous_cancellations":**

In [ ]:
df["previous_cancellations"].value_counts(dropna=False)

,count
previous_cancellations,
0,59079
0,53827
1,6024
2,116
24,48
11,35
tri,33
3,32
4,31


In [ ]:
df['previous_cancellations'].unique()

array(['0', '1', '2', 'tri', 'dvašest', '26', '25', '14', '3', '4', '24',
       '19', 'jedandevet', '5', 0, '21', '6', '13', 'jedantri', '11', 1],
      dtype=object)

In [ ]:
cancellations_map = {
    "tri": 3,
    "jedandevet": 19,
    "dvašest": 26,
    "jedantri": 13
}

df["previous_cancellations"] = df["previous_cancellations"].replace(cancellations_map)

In [ ]:
df["previous_cancellations"] = df["previous_cancellations"].astype("int")

In [ ]:
df['previous_cancellations'].unique()

array([ 0,  1,  2,  3, 26, 25, 14,  4, 24, 19,  5, 21,  6, 13, 11])

In [ ]:
df["previous_cancellations"].value_counts(dropna=False)

,count
previous_cancellations,
0,112906
1,6051
2,116
3,65
24,48
11,35
4,31
26,26
25,25


**Kolona "previous_bookings_not_canceled":**

In [ ]:
df["previous_bookings_not_canceled"].value_counts(dropna=False)

,count
previous_bookings_not_canceled,
0,76233
0x0,39537
1,1002
0x1,540
2,377
...,...
0x45,1
72,1
71,1


In [ ]:
df['previous_bookings_not_canceled'].unique()

array(['0', '0x0', '1', '2', '3', '0x1', '0x2', '0x3', '0x4', '5', '0x5',
       '0x6', '7', '8', '4', '6', '0x7', '9', '10', '11', '12', '0x8',
       '0x9', '0xc', '0xd', '13', '14', '0xf', '16', '0x11', '18', '0x12',
       '0x14', '21', '0x16', '0x17', '24', '25', '27', '0x1c', '0x1d',
       '30', '0xa', '0xb', '0x10', '0x13', '0x15', '23', '0x19', '26',
       '0xe', '15', '17', '19', '20', '22', '28', '31', '0x20', '29',
       '33', '34', '0x23', '36', '37', '38', '0x27', '40', '41', '42',
       '43', '44', '45', '46', '0x2f', '0x30', '48', '49', '50', '0x33',
       '0x34', '53', '54', '55', '0x38', '57', '58', '0x3b', '60', '0x3d',
       '62', '0x3f', '0x40', '65', '66', '0x43', '68', '0x45', '70', '71',
       '72', '0x18', '0x1a', '0x1e', '0x1b'], dtype=object)

In [ ]:
def hex_to_int(val):
    if isinstance(val, str) and val.startswith("0x"):
        return int(val, 16)
    return int(val)

df["previous_bookings_not_canceled"] = df["previous_bookings_not_canceled"].apply(hex_to_int)

In [ ]:
df["previous_bookings_not_canceled"] = df["previous_bookings_not_canceled"].astype("int")

In [ ]:
df['previous_bookings_not_canceled'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 19, 26, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72])

In [ ]:
df["previous_bookings_not_canceled"].value_counts(dropna=False)

,count
previous_bookings_not_canceled,
0,115770
1,1542
2,580
3,333
4,229
...,...
68,1
69,1
70,1


**Kolona "reserved_room_type":**

In [ ]:
df["reserved_room_type"].value_counts(dropna=False)

,count
reserved_room_type,
A,45940
65,40054
D,10157
68,9044
E,3503
69,3032
F,1529
70,1368
G,1166


In [ ]:
df['reserved_room_type'].unique()

array(['67', '65', 'A', 'C', 'D', '69', '68', 'G', 'E', 'F', '71', '70',
       '72', 'H', 'L', '80', 'P', 'B', '66'], dtype=object)

In [ ]:
def ascii_to_char(val):
    if val.isdigit():
        return chr(int(val))
    return val

df["reserved_room_type"] = df["reserved_room_type"].apply(ascii_to_char)

In [ ]:
df['reserved_room_type'].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'H', 'L', 'P', 'B'], dtype=object)

In [ ]:
df["reserved_room_type"].value_counts(dropna=False)

,count
reserved_room_type,
A,85994
D,19201
E,6535
F,2897
G,2094
B,1118
C,932
H,601
P,12


**Kolona "assigned_room_type":**

In [ ]:
df["assigned_room_type"].value_counts(dropna=False)

,count
assigned_room_type,
A,74053
D,16535
0,8787
E,7806
F,3751
C,2375
G,1673
B,1443
6,880


In [ ]:
room_type_map = {
    "0": "D",
    "6": "G",
    "1": "I",
    "8": "B"
}

df["assigned_room_type"] = df["assigned_room_type"].replace(room_type_map)

In [ ]:
df['assigned_room_type'].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'P', 'L', 'K'],
      dtype=object)

In [ ]:
df["assigned_room_type"].value_counts(dropna=False)

,count
assigned_room_type,
A,74053
D,25322
E,7806
F,3751
G,2553
C,2375
B,2163
H,712
I,363


**Kolona "booking_changes":**

In [ ]:
df["booking_changes"].value_counts(dropna=False)

,count
booking_changes,
0,55723
no changes,45591
1,12701
2,3805
3,927
4,376
5,118
6,63
7,31


In [ ]:
df.loc[df["booking_changes"] == "no changes", "booking_changes"] = "0"

In [ ]:
df["booking_changes"] = df["booking_changes"].astype("int")

In [ ]:
df['booking_changes'].unique()

array([ 3,  4,  0,  1,  2,  5, 17,  6,  8,  7, 10, 16,  9, 13, 12, 20, 14,
       15, 11, 21, 18])

In [ ]:
df["booking_changes"].value_counts(dropna=False)

,count
booking_changes,
0,101314
1,12701
2,3805
3,927
4,376
5,118
6,63
7,31
8,17


**Kolona "deposit_type":**

In [ ]:
df["deposit_type"].value_counts(dropna=False)

,count
deposit_type,
No Deposit,43949
1,23221
0,23181
2,22844
Non Refund,6125
Refundable,70


In [ ]:
deposit_map = {
    "0": "No Deposit",
    "1": "Non Refund",
    "2": "Refundable"
}

df["deposit_type"] = df["deposit_type"].replace(deposit_map)
df["deposit_type"] = df["deposit_type"].astype("string")

In [ ]:
df['deposit_type'].unique()

<StringArray>
['No Deposit', 'Non Refund', 'Refundable']
Length: 3, dtype: string

In [ ]:
df["deposit_type"].value_counts(dropna=False)

,count
deposit_type,
No Deposit,67130
Non Refund,29346
Refundable,22914


**Kolona "agent":**

In [ ]:
df["agent"].value_counts(dropna=False)

,count
agent,
9.0,19763
NaN,16340
0o11,12198
240.0,8693
0o360,5229
...,...
341.0,1
346.0,1
283.0,1


In [ ]:
df = df.drop(columns=["agent"])

**Kolona "company":**

In [ ]:
df["company"].value_counts(dropna=False)

,count
company,
NaN,112593
****,659
**|**|***,567
40.0,269
****|*****,266
...,...
351.0,1
417.0,1
243.0,1


In [ ]:
df['company'].unique()

array([nan, '*|*', '110.0', '113.0', '270.0', '*|*******|********',
       '**|****', '*|*****|****', '178.0', '*|****|****', '***|*******',
       '307.0', '**|******|********', '268.0', '154.0', '*****|*********',
       '204.0', '***|*|**', '***|*|********', '*********|****',
       '*|*******|****', '274.0', '174.0', '*|*********|*****',
       '**|**|***', '223.0', '317.0', '***|*|*******', '**|********|*',
       '*|*|********', '281.0', '*****|***', '**|********|******', '*|**',
       '47.0', '***|**|****', '324.0', '***|****|**', '342.0',
       '***|*******|***', '286.0', '371.0', '383.0', '********|******',
       '********|**', '82.0', '218.0', '********|********', '*|*|***',
       '***|*', '31.0', '****|*******', '***|*********|*******', '392.0',
       '405.0', '***|***|*', '367.0', '***|******|*******', '20.0', '**',
       '********|***', '83.0', '****|*|******', '*****|*', '53.0',
       '395.0', '***|****', '********|****', '***|******', '****|*****',
       '394.0',

In [ ]:
df = df.drop(columns=["company"])

**Kolona "days_in_waiting_list":**

In [ ]:
df["days_in_waiting_list"].value_counts(dropna=False)

,count
days_in_waiting_list,
0 mjeseci i 0 dana,63660
0,52032
1 mjeseci i 9 dana,125
39,102
1 mjeseci i 28 dana,84
...,...
3 mjeseci i 2 dana,1
2 mjeseci i 14 dana,1
5 mjeseci i 17 dana,1


In [ ]:
df['days_in_waiting_list'].unique()

array(['0 mjeseci i 0 dana', '0', '50', '47', '1 mjeseci i 17 dana',
       '2 mjeseci i 5 dana', '65', '4 mjeseci i 2 dana', '122',
       '2 mjeseci i 15 dana', '75', '3 mjeseci i 11 dana', '101',
       '5 mjeseci i 0 dana', '150', '125', '4 mjeseci i 5 dana', '14',
       '60', '1 mjeseci i 4 dana', '1 mjeseci i 20 dana', '100', '22',
       '121', '61', '39', '5', '0 mjeseci i 5 dana', '0 mjeseci i 1 dana',
       '0 mjeseci i 8 dana', '1', '3 mjeseci i 17 dana', '43',
       '1 mjeseci i 22 dana', '2', '0 mjeseci i 11 dana', '142', '116',
       '13', '44', '3 mjeseci i 7 dana', '97', '2 mjeseci i 23 dana', '4',
       '0 mjeseci i 14 dana', '0 mjeseci i 4 dana', '113',
       '3 mjeseci i 23 dana', '18', '0 mjeseci i 20 dana', '185',
       '6 mjeseci i 5 dana', '107', '93', '109', '34', '6',
       '0 mjeseci i 6 dana', '2 mjeseci i 0 dana', '1 mjeseci i 7 dana',
       '1 mjeseci i 13 dana', '105', '3 mjeseci i 10 dana',
       '5 mjeseci i 4 dana', '64', '2 mjeseci i 4 dana',

In [ ]:
import re
def parse_waiting(val):
    if pd.isna(val):
        return np.nan

    if re.fullmatch(r"\d+", str(val).strip()):
        return int(val)

    m = re.match(r"(\d+)\s+mjeseci\s+i\s+(\d+)\s+dana", str(val))
    if m:
        months = int(m.group(1))
        days = int(m.group(2))
        return months * 30 + days

    return np.nan

df["days_in_waiting_list"] = df["days_in_waiting_list"].apply(parse_waiting)
df["days_in_waiting_list"] = df["days_in_waiting_list"].astype("int")

In [ ]:
df['days_in_waiting_list'].unique()

array([  0,  50,  47,  65, 122,  75, 101, 150, 125,  14,  60,  34, 100,
        22, 121,  61,  39,   5,   1,   8, 107,  43,  52,   2,  11, 142,
       116,  13,  44,  97,  83,   4, 113,  18,  20, 185,  93, 109,   6,
        37, 105, 154,  64,  99,  38,  48,  33,  77,  21,  80,  59,  40,
        58,  89,  53,  49,  69,  87,  91,  57, 111,  79,  98,  85,  63,
        15,   3,  41, 224,  31,  56, 187, 176,  71,  55,  96, 236, 259,
       207, 215, 160, 120,  30,  32,  27,  62,  24, 108, 147, 379,  70,
        35, 178, 330, 223, 174, 162, 391,  68, 193,  10,  76,  16,  28,
         9, 165,  17,  25,  46,   7,  84, 175, 183,  23, 117,  12,  54,
        26,  73,  45,  19,  42,  72,  81,  92,  74, 167,  36])

In [ ]:
df["days_in_waiting_list"].value_counts(dropna=False)

,count
days_in_waiting_list,
0,115692
39,227
58,164
44,141
31,127
...,...
81,1
92,1
74,1


**Kolona "customer_type":**

In [ ]:
df["customer_type"].value_counts(dropna=False)

,count
customer_type,
Transient,59176
Transient-Party,16591
Contract,2703
Group,395
trANSieNt,83
...,...
TransIENT-PArTY,1
TRAnSIEnt-PaRtY,1
trANsIEnt-ParTY,1


In [ ]:
def clean_customer_type(val):
    if pd.isna(val):
        return val

    val = str(val).lower()

    parts = val.split("-")

    parts = [p.capitalize() for p in parts]

    return "-".join(parts)

df["customer_type"] = df["customer_type"].apply(clean_customer_type)

In [ ]:
df['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [ ]:
df["customer_type"].value_counts(dropna=False)

,count
customer_type,
Transient,89613
Transient-Party,25124
Contract,4076
Group,577


**Kolona "adr":**

In [ ]:
df["adr"].value_counts(dropna=False)

,count
adr,
62.0,1966
62+0.0,1788
75.0,1445
90.0,1322
65.0,1296
...,...
95.12,1
173.73,1
113+0.98,1


In [ ]:
df['adr'].unique()

array(['0+0.0', '75.0', '75+0.0', ..., '96+0.14', '225+0.43', '157.71'],
      dtype=object)

In [ ]:
def clean_adr(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip()
    try:
      if "+" in val:
        try:
            parts = val.split("+")
            nums = [float(p) for p in parts]
            return sum(nums)
        except:
            return np.nan

      if float(val).is_integer():
            return int(val)
      return float(val)
    except:
        return val

df["adr"] = df["adr"].apply(clean_adr)

In [ ]:
df["adr"].value_counts(dropna=False)

,count
adr,
62.0,1966
62.0,1788
75.0,1445
90.0,1322
65.0,1296
...,...
95.12,1
173.73,1
116.99,1


**Kolona "required_car_parking_spaces":**

In [ ]:
df["required_car_parking_spaces"].value_counts(dropna=False)

,count
required_car_parking_spaces,
0,70525
nemam auto :(,41449
1,4672
imam jedan autic,2711
2,28
3,3
8,2


In [ ]:
df.loc[df["required_car_parking_spaces"] == "nemam auto :(", "required_car_parking_spaces"] = "0"

In [ ]:
df.loc[df["required_car_parking_spaces"] == "imam jedan autic", "required_car_parking_spaces"] = "1"

In [ ]:
df['required_car_parking_spaces'].unique()

array(['0', '1', '2', '8', '3'], dtype=object)

In [ ]:
df["required_car_parking_spaces"] = df["required_car_parking_spaces"].astype("int")

In [ ]:
df["required_car_parking_spaces"].value_counts(dropna=False)

,count
required_car_parking_spaces,
0,111974
1,7383
2,28
3,3
8,2


**Kolona "total_of_special_requests":**

In [ ]:
df["total_of_special_requests"].value_counts(dropna=False)

,count
total_of_special_requests,
nula,45044
0,25274
nedovoljan,21226
1,12000
dovoljan,8311
2,4658
dobar,1572
3,925
vrlo dobar,232


In [ ]:
grades_mapping = {
    'nula': 0,
    'nedovoljan': 1,
    'dovoljan': 2,
    'dobar': 3,
    'vrlo dobar': 4,
    'odlican': 5,
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5
}

df['total_of_special_requests'] = df['total_of_special_requests'].replace(grades_mapping)

/tmp/ipython-input-1237378472.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['total_of_special_requests'] = df['total_of_special_requests'].replace(grades_mapping)


In [ ]:
df['total_od_special_requests'] = df['total_of_special_requests'].astype(int)

In [ ]:
df['total_of_special_requests'].unique()

array([0, 1, 3, 2, 4, 5])

In [ ]:
df["total_of_special_requests"].value_counts(dropna=False)

,count
total_of_special_requests,
0,70318
1,33226
2,12969
3,2497
4,340
5,40


**Kolona "reservation_status":**

In [ ]:
df["reservation_status"].value_counts(dropna=False)

,count
reservation_status,
0000,39099
Check-Out,36067
0001,22354
Canceled,20663
0010,630
No-Show,577


In [ ]:
df['reservation_status'].unique()

array(['0000', 'Check-Out', '0001', 'Canceled', '0010', 'No-Show'],
      dtype=object)

In [ ]:
reservations = {
    '0000': "Check-Out",
    '0001': "Canceled",
    '0010': "No-Show"
}

df['reservation_status'] = df['reservation_status'].replace(reservations)
df["reservation_status"] = df["reservation_status"].astype("string")

In [ ]:
df["reservation_status"].value_counts(dropna=False)

,count
reservation_status,
Check-Out,75166
Canceled,43017
No-Show,1207


**Kolona "reservation_status_date":**

In [ ]:
df["reservation_status_date"].value_counts(dropna=False)

,count
reservation_status_date,
21/10/2015,942
2015-10-21,519
25/11/2016,512
06/07/2015,499
01/01/2015,488
...,...
2015-03-23,1
2015-04-27,1
2015-06-10,1


In [ ]:
import pandas as pd
import re

def fix_reservation_date(val):
    if pd.isna(val):
        return val

    val = str(val).strip()

    if re.match(r"^\d{2}/\d{2}/\d{4}$", val):
        try:
            return pd.to_datetime(val, format="%d/%m/%Y").strftime("%Y-%m-%d")
        except:
            return val

    if re.match(r"^\d{4}-\d{2}-\d{2}$", val):
        return val

    return val

df["reservation_status_date"] = df["reservation_status_date"].apply(fix_reservation_date)

In [ ]:
df["reservation_status_date"].value_counts(dropna=False)

,count
reservation_status_date,
2015-10-21,1461
2015-07-06,805
2016-11-25,790
2015-01-01,763
2016-01-18,625
...,...
2015-02-26,1
2015-03-18,1
2015-03-12,1


In [ ]:
df.to_csv("/content/hotel_ociscen.csv", index=False)

In [ ]:
df.to_csv("/content/drive/MyDrive/MU Projekat/hotel_ociscen.csv", index=False)

In [ ]:
#greškom u kucanju dodana nova kolona
df1 = pd.read_csv('/content/drive/MyDrive/MU Projekat/hotel_ociscen.csv')

In [ ]:
df1 = df1.drop(columns=["total_od_special_requests"])

In [ ]:
df1.to_csv("/content/drive/MyDrive/MU Projekat/hotel_ociscen.csv", index=False)